id: 972c0e8f41da49e2812606b9a66ff7d4
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_115-The_Display_of_the_Pure_Land_of_Sukhavati-v1
  language: bo
  author: ''
  volume: {}
